services:
  laravel.test:
    build:
      context: .
      dockerfile: docker/laravel/Dockerfile
    image: pgnserver-app
    ports:
      - ${APP_PORT:-8000}:8000
    environment:
      APP_ENV: ${APP_ENV:-local}
      APP_DEBUG: ${APP_DEBUG:-true}
      APP_TIMEZONE: ${APP_TIMEZONE:-Asia/Jakarta}
      DB_HOST: pgsql
      DB_PORT: 5432
      DB_CONNECTION: ${DB_CONNECTION:-pgsql}
      DB_DATABASE: ${DB_DATABASE:-pgn_server}
      DB_USERNAME: ${DB_USERNAME:-pgn_server}
      DB_PASSWORD: ${DB_PASSWORD:-password_lokal_dev}
    volumes:
      - .:/var/www/html
    networks:
      - sail
    depends_on:
      pgsql:
        condition: service_healthy

  pgsql:
    image: postgres:17-alpine
    environment:
      PGPASSWORD: ${DB_PASSWORD:-password_lokal_dev}
      POSTGRES_DB: ${DB_DATABASE:-pgn_server}
      POSTGRES_USER: ${DB_USERNAME:-pgn_server}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password_lokal_dev}
    volumes:
      - pgnserver-pgsql-data:/var/lib/postgresql/data
      - ./vendor/laravel/sail/database/pgsql/create-testing-database.sql:/docker-entrypoint-initdb.d/10-create-testing-database.sql
    networks:
      - sail
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -q -d ${DB_DATABASE:-pgn_server} -U ${DB_USERNAME:-pgn_server}
      retries: 5
      timeout: 5s
      interval: 10s

networks:
  sail:
    driver: bridge

volumes:
  pgnserver-pgsql-data:
    driver: local
