services:
  pgn_db:
    image: postgres:17-alpine
    container_name: pgn_db
    environment:
      POSTGRES_DB: pgn_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      TZ: Asia/Jakarta
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - ./docker/pgdata:/var/lib/postgresql/data
    networks:
      - pgn_jaringan
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d pgn_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgn_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pgn_api
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      pgn_db:
        condition: service_healthy
    environment:
      - DB_HOST=pgn_db
      - DB_PORT=5432
      - DB_USER=admin
      - DB_PASSWORD=admin
      - DB_NAME=pgn_db
      - APP_PORT=8080
      - JWT_SECRET=pgn-rahasia-2026
      - TZ=Asia/Jakarta
    networks:
      - pgn_jaringan
    volumes:
      - ./penyimpanan:/app/penyimpanan

networks:
  pgn_jaringan:
    driver: bridge
