<?php

declare(strict_types=1);

namespace App\Support\Errors;

enum KodeKesalahanApi: string
{
    case SERVER_SEHAT = 'SERVER_SEHAT';
    case DATABASE_TIDAK_TERHUBUNG = 'DATABASE_TIDAK_TERHUBUNG';
    case AUTENTIKASI_GAGAL = 'AUTENTIKASI_GAGAL';
    case VALIDASI_GAGAL = 'VALIDASI_GAGAL';
    case KONFLIK_IDEMPOTENCY = 'KONFLIK_IDEMPOTENCY';
    case PEMERIKSAAN_HARIAN_SUDAH_ADA = 'PEMERIKSAAN_HARIAN_SUDAH_ADA';
    case TEMPLATE_DEFECT_TIDAK_VALID = 'TEMPLATE_DEFECT_TIDAK_VALID';
    case TOTAL_DEFECT_MELEBIHI_TOTAL_CHECK = 'TOTAL_DEFECT_MELEBIHI_TOTAL_CHECK';
    case DATA_TIDAK_DITEMUKAN = 'DATA_TIDAK_DITEMUKAN';
    case KESALAHAN_SERVER = 'KESALAHAN_SERVER';
}
