// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/analitik/lacak": {
            "get": {
                "description": "Menelusuri defects produk hingga ke level bahan baku pembentuk \u0026 supplier",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Analitik"
                ],
                "summary": "Lacak Akar Masalah Defect (BOM Tracing)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Kode Defect Cacat",
                        "name": "kode_cacat",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "SKU Produk Jadi (Finished Good)",
                        "name": "parent_sku",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/respon.ResponStandar"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/respon.ResponStandar"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/respon.ResponStandar"
                        }
                    }
                }
            }
        },
        "/api/v1/analitik/metrik_pareto_bulanan": {
            "get": {
                "description": "Mengembalikan kalkulasi Pareto 80/20 per bulan menggunakan Window Function SQL",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Analitik"
                ],
                "summary": "Dapatkan Metrik Pareto Bulanan",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Bulan (1-12)",
                        "name": "bulan",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Tahun (contoh: 2026)",
                        "name": "tahun",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/respon.ResponStandar"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/respon.ResponStandar"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/respon.ResponStandar"
                        }
                    }
                }
            }
        },
        "/api/v1/analitik/pareto": {
            "get": {
                "description": "Mengembalikan kalkulasi Pareto 80/20 berdasarkan tanggal mulai, tanggal selesai, dan lini.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Analitik"
                ],
                "summary": "Dapatkan Pareto Dinamis",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Tanggal Mulai (YYYY-MM-DD)",
                        "name": "start_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Tanggal Selesai (YYYY-MM-DD)",
                        "name": "end_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Nama Lini / Zona",
                        "name": "line",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/respon.ResponStandar"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/respon.ResponStandar"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/respon.ResponStandar"
                        }
                    }
                }
            }
        },
        "/api/v1/materials/{id}/media": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Menyimpan foto atau bukti cacat terkait suatu material",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Media"
                ],
                "summary": "Unggah Media Material",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID Material",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "Berkas gambar (JPG/PNG, Maks 5MB)",
                        "name": "berkas",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/respon.ResponStandar"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/respon.ResponStandar"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/respon.ResponStandar"
                        }
                    }
                }
            }
        },
        "/api/v1/media/{id}/pratinjau": {
            "get": {
                "description": "Merender berkas media ke peramban",
                "produces": [
                    "image/jpeg"
                ],
                "tags": [
                    "Media"
                ],
                "summary": "Pratinjau Media",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID Media",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "file"
                        }
                    }
                }
            }
        },
        "/api/v1/operasi/rekam_lembar_periksa": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Menyimpan entri lembar periksa beserta detail inspeksinya",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Kualitas"
                ],
                "summary": "Rekam Lembar Periksa",
                "parameters": [
                    {
                        "description": "Payload Lembar Periksa",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/kualitas.DTOLembarPeriksaKirim"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/respon.ResponStandar"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/respon.ResponStandar"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/respon.ResponStandar"
                        }
                    }
                }
            }
        },
        "/api/v1/operasi/riwayat_lembar_periksa": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Menampilkan daftar historis lembar periksa dengan filter kalender",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Kualitas"
                ],
                "summary": "Riwayat Lembar Periksa",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Batas jumlah data (default 10)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Offset paginasi (default 0)",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter tanggal mulai (YYYY-MM-DD)",
                        "name": "tanggal_mulai",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter tanggal selesai (YYYY-MM-DD)",
                        "name": "tanggal_selesai",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter zona lini",
                        "name": "zona_lini",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/respon.ResponStandar"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/respon.ResponStandar"
                        }
                    }
                }
            }
        },
        "/api/v1/otentikasi/daftar": {
            "post": {
                "description": "Mendaftarkan kredensial staf QC/Manajemen baru",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Otentikasi"
                ],
                "summary": "Pendaftaran Pengguna",
                "parameters": [
                    {
                        "description": "Data pendaftaran",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/otentikasi.DataPermintaanRegistrasi"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/respon.ResponStandar"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/respon.ResponStandar"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/respon.ResponStandar"
                        }
                    }
                }
            }
        },
        "/api/v1/otentikasi/keluar": {
            "post": {
                "description": "Mengakhiri sesi pengguna (Client-side token drop)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Otentikasi"
                ],
                "summary": "Akses Keluar",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/respon.ResponStandar"
                        }
                    }
                }
            }
        },
        "/api/v1/otentikasi/lupa-sandi": {
            "post": {
                "description": "Pemulihan akun QC",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Otentikasi"
                ],
                "summary": "Lupa Sandi",
                "parameters": [
                    {
                        "description": "Permohonan Reset",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/otentikasi.DataPermintaanLupaSandi"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/respon.ResponStandar"
                        }
                    }
                }
            }
        },
        "/api/v1/otentikasi/masuk": {
            "post": {
                "description": "Memberikan Token JWT untuk akses sesi internal",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Otentikasi"
                ],
                "summary": "Akses Masuk Pengguna",
                "parameters": [
                    {
                        "description": "Kredensial",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/otentikasi.DataPermintaanLogin"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/respon.ResponStandar"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/respon.ResponStandar"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "kualitas.DTODetailInspeksi": {
            "type": "object",
            "required": [
                "kodeCacat",
                "unikPartId",
                "waktuPergeseran"
            ],
            "properties": {
                "kodeCacat": {
                    "type": "string"
                },
                "rasioCacat": {
                    "description": "NG",
                    "type": "number",
                    "minimum": 0
                },
                "rasioTotalOK": {
                    "type": "number",
                    "minimum": 0
                },
                "totalProduksi": {
                    "type": "number",
                    "minimum": 0
                },
                "unikPartId": {
                    "type": "integer"
                },
                "waktuPergeseran": {
                    "description": "Shift",
                    "type": "string"
                }
            }
        },
        "kualitas.DTOLembarPeriksaKirim": {
            "type": "object",
            "required": [
                "detail",
                "penggunaIdTercatat",
                "tanggal",
                "zonaLini"
            ],
            "properties": {
                "detail": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/kualitas.DTODetailInspeksi"
                    }
                },
                "penggunaIdTercatat": {
                    "type": "integer"
                },
                "tanggal": {
                    "type": "string"
                },
                "zonaLini": {
                    "type": "string"
                }
            }
        },
        "otentikasi.DataPermintaanLogin": {
            "type": "object",
            "required": [
                "sandi",
                "surel"
            ],
            "properties": {
                "sandi": {
                    "type": "string"
                },
                "surel": {
                    "type": "string"
                }
            }
        },
        "otentikasi.DataPermintaanLupaSandi": {
            "type": "object",
            "required": [
                "sandiBaru",
                "surel"
            ],
            "properties": {
                "sandiBaru": {
                    "type": "string",
                    "minLength": 8
                },
                "surel": {
                    "type": "string"
                }
            }
        },
        "otentikasi.DataPermintaanRegistrasi": {
            "type": "object",
            "required": [
                "sandi",
                "surel"
            ],
            "properties": {
                "peran": {
                    "type": "string"
                },
                "sandi": {
                    "type": "string",
                    "minLength": 8
                },
                "surel": {
                    "type": "string"
                }
            }
        },
        "respon.ResponStandar": {
            "type": "object",
            "properties": {
                "data": {},
                "errors": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "message": {
                    "type": "string"
                },
                "status": {
                    "description": "\"success\" atau \"fail\" atau \"error\"",
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "PGNServer API",
	Description:      "REST API untuk ekosistem manufaktur dan kontrol kualitas PGNServer.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
