// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/analitik/lacak": {
            "get": {
                "description": "Menelusuri defects produk hingga ke level bahan baku pembentuk \u0026 supplier",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Analitik"
                ],
                "summary": "Lacak Akar Masalah Defect (BOM Tracing)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Kode Defect Cacat",
                        "name": "kode_cacat",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "SKU Produk Jadi (Finished Good)",
                        "name": "parent_sku",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/respon.ResponStandar"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/respon.ResponStandar"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/respon.ResponStandar"
                        }
                    }
                }
            }
        },
        "/api/v1/analitik/metrik_pareto_bulanan": {
            "get": {
                "description": "Mengembalikan kalkulasi Pareto 80/20 per bulan menggunakan Window Function SQL",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Analitik"
                ],
                "summary": "Dapatkan Metrik Pareto Bulanan",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Bulan (1-12)",
                        "name": "bulan",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Tahun (contoh: 2026)",
                        "name": "tahun",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/respon.ResponStandar"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/respon.ResponStandar"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/respon.ResponStandar"
                        }
                    }
                }
            }
        },
        "/api/v1/analitik/pareto": {
            "get": {
                "description": "Mengembalikan kalkulasi Pareto 80/20 berdasarkan tanggal mulai, tanggal selesai, dan lini.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Analitik"
                ],
                "summary": "Dapatkan Pareto Dinamis",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Tanggal Mulai (YYYY-MM-DD)",
                        "name": "start_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Tanggal Selesai (YYYY-MM-DD)",
                        "name": "end_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Nama Lini / Zona",
                        "name": "line",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/respon.ResponStandar"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/respon.ResponStandar"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/respon.ResponStandar"
                        }
                    }
                }
            }
        },
        "/api/v1/boms": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Menampilkan daftar seluruh relasi BOM beserta detail material terkait",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Manufaktur - BOM"
                ],
                "summary": "Ambil Semua BOM",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/respon.ResponStandar"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/manufaktur.KomposisiMaterialBOM"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/respon.ResponStandar"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/respon.ResponStandar"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Menyimpan relasi hirarkis BOM baru ke pangkalan data",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Manufaktur - BOM"
                ],
                "summary": "Tambah BOM Baru",
                "parameters": [
                    {
                        "description": "Payload Tambah BOM",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/manufaktur.DTOBOMSimpan"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/respon.ResponStandar"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/manufaktur.KomposisiMaterialBOM"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/respon.ResponStandar"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/respon.ResponStandar"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/respon.ResponStandar"
                        }
                    }
                }
            }
        },
        "/api/v1/boms/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Mendapatkan data detail relasi BOM berdasarkan ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Manufaktur - BOM"
                ],
                "summary": "Detail BOM",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID BOM",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/respon.ResponStandar"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/manufaktur.KomposisiMaterialBOM"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/respon.ResponStandar"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/respon.ResponStandar"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Memperbarui informasi relasi BOM berdasarkan ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Manufaktur - BOM"
                ],
                "summary": "Perbarui BOM",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID BOM",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Payload Perbarui BOM",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/manufaktur.DTOBOMSimpan"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/respon.ResponStandar"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/manufaktur.KomposisiMaterialBOM"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/respon.ResponStandar"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/respon.ResponStandar"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/respon.ResponStandar"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Menghapus data relasi BOM dari sistem berdasarkan ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Manufaktur - BOM"
                ],
                "summary": "Hapus BOM",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID BOM",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/respon.ResponStandar"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/respon.ResponStandar"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/respon.ResponStandar"
                        }
                    }
                }
            }
        },
        "/api/v1/cek_sistem": {
            "get": {
                "description": "Memvalidasi kesiapan server API dan konektivitas live database",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sistem"
                ],
                "summary": "Pemeriksaan Kesehatan Sistem",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/respon.ResponStandar"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/respon.ResponStandar"
                        }
                    }
                }
            }
        },
        "/api/v1/customers": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Menampilkan daftar seluruh customer",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Manufaktur - Customer"
                ],
                "summary": "Ambil Semua Customer",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/respon.ResponStandar"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/manufaktur.Customer"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/respon.ResponStandar"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/respon.ResponStandar"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Menyimpan data customer baru ke pangkalan data",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Manufaktur - Customer"
                ],
                "summary": "Tambah Customer Baru",
                "parameters": [
                    {
                        "description": "Payload Tambah Customer",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/manufaktur.DTOCustomerSimpan"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/respon.ResponStandar"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/manufaktur.Customer"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/respon.ResponStandar"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/respon.ResponStandar"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/respon.ResponStandar"
                        }
                    }
                }
            }
        },
        "/api/v1/customers/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Mendapatkan data detail customer berdasarkan ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Manufaktur - Customer"
                ],
                "summary": "Detail Customer",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID Customer",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/respon.ResponStandar"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/manufaktur.Customer"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/respon.ResponStandar"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/respon.ResponStandar"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Memperbarui informasi customer berdasarkan ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Manufaktur - Customer"
                ],
                "summary": "Perbarui Customer",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID Customer",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Payload Perbarui Customer",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/manufaktur.DTOCustomerSimpan"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/respon.ResponStandar"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/manufaktur.Customer"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/respon.ResponStandar"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/respon.ResponStandar"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/respon.ResponStandar"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Menghapus data customer dari sistem berdasarkan ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Manufaktur - Customer"
                ],
                "summary": "Hapus Customer",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID Customer",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/respon.ResponStandar"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/respon.ResponStandar"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/respon.ResponStandar"
                        }
                    }
                }
            }
        },
        "/api/v1/health": {
            "get": {
                "description": "Memvalidasi bahwa instansi server API aktif dan berjalan",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sistem"
                ],
                "summary": "Pemeriksaan Liveness Aplikasi",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/respon.ResponStandar"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/respon.ResponStandar"
                        }
                    }
                }
            }
        },
        "/api/v1/kesehatan": {
            "get": {
                "description": "Memvalidasi kesiapan server API dan konektivitas live database untuk klien KMP",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sistem"
                ],
                "summary": "Pemeriksaan Kesehatan Sistem KMP",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/respon.ResponStandar"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/respon.ResponStandar"
                        }
                    }
                }
            }
        },
        "/api/v1/krusial/status": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Menyajikan data status sensitif jika IP pengirim lolos Whitelisting korporasi",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sistem"
                ],
                "summary": "Status Operasi Krusial (Whitelisted IP)",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/respon.ResponStandar"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/respon.ResponStandar"
                        }
                    }
                }
            }
        },
        "/api/v1/master-data/snapshot": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Mengambil snapshot data master lengkap untuk sinkronisasi offline-first klien QControl",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Manufaktur - Master Data"
                ],
                "summary": "Snapshot master data untuk QControl",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/respon.ResponStandar"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/manufaktur.MasterDataSnapshotDto"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/respon.ResponStandar"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/respon.ResponStandar"
                        }
                    }
                }
            }
        },
        "/api/v1/materials": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Menampilkan daftar seluruh material beserta info pemasoknya",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Manufaktur - Material"
                ],
                "summary": "Ambil Semua Material",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/respon.ResponStandar"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/manufaktur.Material"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/respon.ResponStandar"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/respon.ResponStandar"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Menyimpan data material baru ke pangkalan data",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Manufaktur - Material"
                ],
                "summary": "Tambah Material Baru",
                "parameters": [
                    {
                        "description": "Payload Tambah Material",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/manufaktur.DTOMaterialSimpan"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/respon.ResponStandar"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/manufaktur.Material"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/respon.ResponStandar"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/respon.ResponStandar"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/respon.ResponStandar"
                        }
                    }
                }
            }
        },
        "/api/v1/materials/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Mendapatkan data detail material berdasarkan ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Manufaktur - Material"
                ],
                "summary": "Detail Material",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID Material",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/respon.ResponStandar"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/manufaktur.Material"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/respon.ResponStandar"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/respon.ResponStandar"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Memperbarui informasi material berdasarkan ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Manufaktur - Material"
                ],
                "summary": "Perbarui Material",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID Material",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Payload Perbarui Material",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/manufaktur.DTOMaterialSimpan"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/respon.ResponStandar"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/manufaktur.Material"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/respon.ResponStandar"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/respon.ResponStandar"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/respon.ResponStandar"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Menghapus data material dari sistem berdasarkan ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Manufaktur - Material"
                ],
                "summary": "Hapus Material",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID Material",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/respon.ResponStandar"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/respon.ResponStandar"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/respon.ResponStandar"
                        }
                    }
                }
            }
        },
        "/api/v1/materials/{id}/media": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Menyimpan foto atau bukti cacat terkait suatu material",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Media"
                ],
                "summary": "Unggah Media Material",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID Material",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "Berkas gambar (JPG/PNG, Maks 5MB)",
                        "name": "berkas",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/respon.ResponStandar"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/respon.ResponStandar"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/respon.ResponStandar"
                        }
                    }
                }
            }
        },
        "/api/v1/media/{id}/pratinjau": {
            "get": {
                "description": "Merender berkas media ke peramban",
                "produces": [
                    "image/jpeg"
                ],
                "tags": [
                    "Media"
                ],
                "summary": "Pratinjau Media",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID Media",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "file"
                        }
                    }
                }
            }
        },
        "/api/v1/operasi/rekam_lembar_periksa": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Menyimpan entri lembar periksa beserta detail inspeksinya",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Kualitas"
                ],
                "summary": "Rekam Lembar Periksa",
                "parameters": [
                    {
                        "description": "Payload Lembar Periksa",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/kualitas.DTOLembarPeriksaKirim"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/respon.ResponStandar"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/respon.ResponStandar"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/respon.ResponStandar"
                        }
                    }
                }
            }
        },
        "/api/v1/operasi/riwayat_lembar_periksa": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Menampilkan daftar historis lembar periksa dengan filter kalender",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Kualitas"
                ],
                "summary": "Riwayat Lembar Periksa",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Batas jumlah data (default 10)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Offset paginasi (default 0)",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter tanggal mulai (YYYY-MM-DD)",
                        "name": "tanggal_mulai",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter tanggal selesai (YYYY-MM-DD)",
                        "name": "tanggal_selesai",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter zona lini",
                        "name": "zona_lini",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/respon.ResponStandar"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/respon.ResponStandar"
                        }
                    }
                }
            }
        },
        "/api/v1/otentikasi/daftar": {
            "post": {
                "description": "Mendaftarkan kredensial staf QC/Manajemen baru dengan dukungan retro-kompatibilitas NIP/kata_sandi",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Otentikasi"
                ],
                "summary": "Pendaftaran Pengguna",
                "parameters": [
                    {
                        "description": "Data pendaftaran",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/otentikasi.DataPermintaanRegistrasi"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/respon.ResponStandar"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/respon.ResponStandar"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/respon.ResponStandar"
                        }
                    }
                }
            }
        },
        "/api/v1/otentikasi/keluar": {
            "post": {
                "description": "Mengakhiri sesi pengguna (Client-side token drop)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Otentikasi"
                ],
                "summary": "Akses Keluar",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/respon.ResponStandar"
                        }
                    }
                }
            }
        },
        "/api/v1/otentikasi/lupa-sandi": {
            "post": {
                "description": "Pemulihan akun QC dengan dukungan NIP/kata_sandi fallback",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Otentikasi"
                ],
                "summary": "Lupa Sandi",
                "parameters": [
                    {
                        "description": "Permohonan Reset",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/otentikasi.DataPermintaanLupaSandi"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/respon.ResponStandar"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/respon.ResponStandar"
                        }
                    }
                }
            }
        },
        "/api/v1/otentikasi/masuk": {
            "post": {
                "description": "Memberikan Token JWT untuk akses sesi internal dengan dukungan NIP/kata_sandi",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Otentikasi"
                ],
                "summary": "Akses Masuk Pengguna",
                "parameters": [
                    {
                        "description": "Kredensial",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/otentikasi.DataPermintaanLogin"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/respon.ResponStandar"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/respon.ResponStandar"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/respon.ResponStandar"
                        }
                    }
                }
            }
        },
        "/api/v1/otentikasi/profil": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Menyajikan data profil staf QC/Manajemen yang sedang aktif berdasarkan token JWT",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Otentikasi"
                ],
                "summary": "Data Profil Sesi Pengguna",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/respon.ResponStandar"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/respon.ResponStandar"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/respon.ResponStandar"
                        }
                    }
                }
            }
        },
        "/api/v1/readiness": {
            "get": {
                "description": "Memvalidasi bahwa server API siap menerima trafik dengan memverifikasi koneksi database",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sistem"
                ],
                "summary": "Pemeriksaan Kesiapan Aplikasi",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/respon.ResponStandar"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/respon.ResponStandar"
                        }
                    }
                }
            }
        },
        "/api/v1/suppliers": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Menampilkan daftar seluruh pemasok bahan baku",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Manufaktur - Pemasok"
                ],
                "summary": "Ambil Semua Pemasok",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/respon.ResponStandar"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/manufaktur.Pemasok"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/respon.ResponStandar"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/respon.ResponStandar"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Menyimpan data pemasok (supplier) baru ke pangkalan data",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Manufaktur - Pemasok"
                ],
                "summary": "Tambah Pemasok Baru",
                "parameters": [
                    {
                        "description": "Payload Tambah Pemasok",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/manufaktur.DTOPemasokSimpan"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/respon.ResponStandar"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/manufaktur.Pemasok"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/respon.ResponStandar"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/respon.ResponStandar"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/respon.ResponStandar"
                        }
                    }
                }
            }
        },
        "/api/v1/suppliers/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Mendapatkan data detail pemasok berdasarkan ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Manufaktur - Pemasok"
                ],
                "summary": "Detail Pemasok",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID Pemasok",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/respon.ResponStandar"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/manufaktur.Pemasok"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/respon.ResponStandar"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/respon.ResponStandar"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Memperbarui informasi pemasok berdasarkan ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Manufaktur - Pemasok"
                ],
                "summary": "Perbarui Pemasok",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID Pemasok",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Payload Perbarui Pemasok",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/manufaktur.DTOPemasokSimpan"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/respon.ResponStandar"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/manufaktur.Pemasok"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/respon.ResponStandar"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/respon.ResponStandar"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/respon.ResponStandar"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Menghapus data pemasok dari sistem berdasarkan ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Manufaktur - Pemasok"
                ],
                "summary": "Hapus Pemasok",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID Pemasok",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/respon.ResponStandar"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/respon.ResponStandar"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/respon.ResponStandar"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "kualitas.DTODetailInspeksi": {
            "type": "object",
            "required": [
                "kodeCacat",
                "unikPartId",
                "waktuPergeseran"
            ],
            "properties": {
                "kodeCacat": {
                    "description": "Kode cacat defect (misal: \"A\", \"B\", dll)",
                    "type": "string",
                    "example": "A"
                },
                "rasioCacat": {
                    "description": "Kuantitas barang reject / NG (Not Good)",
                    "type": "number",
                    "minimum": 0,
                    "example": 2
                },
                "rasioTotalOK": {
                    "description": "Kuantitas barang dengan status OK (Lolos QC)",
                    "type": "number",
                    "minimum": 0,
                    "example": 98
                },
                "totalProduksi": {
                    "description": "Total kuantitas barang yang diproduksi",
                    "type": "number",
                    "minimum": 0,
                    "example": 100
                },
                "unikPartId": {
                    "description": "ID unik part material yang diperiksa",
                    "type": "integer",
                    "example": 1
                },
                "waktuPergeseran": {
                    "description": "Waktu/Shift pergeseran jam pemeriksaan",
                    "type": "string",
                    "example": "08:00"
                }
            }
        },
        "kualitas.DTOLembarPeriksaKirim": {
            "type": "object",
            "required": [
                "detail",
                "penggunaIdTercatat",
                "tanggal",
                "zonaLini"
            ],
            "properties": {
                "detail": {
                    "description": "Himpunan baris rincian inspeksi part",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/kualitas.DTODetailInspeksi"
                    }
                },
                "penggunaIdTercatat": {
                    "description": "ID pengguna/staf QC yang merekam data",
                    "type": "integer",
                    "example": 1
                },
                "tanggal": {
                    "description": "Tanggal pemeriksaan (format ISO 8601)",
                    "type": "string",
                    "example": "2026-05-17T00:00:00Z"
                },
                "zonaLini": {
                    "description": "Zona atau Lini produksi tempat inspeksi",
                    "type": "string",
                    "example": "Lini 1"
                }
            }
        },
        "manufaktur.Customer": {
            "type": "object",
            "properties": {
                "customerCode": {
                    "type": "string"
                },
                "dibuatPada": {
                    "type": "string"
                },
                "diubahPada": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "kontak": {
                    "type": "string"
                },
                "nama": {
                    "type": "string"
                }
            }
        },
        "manufaktur.DTOBOMSimpan": {
            "type": "object",
            "required": [
                "idRawMaterial",
                "parameterKuantitasPembentuk"
            ],
            "properties": {
                "idParentMaterial": {
                    "type": "integer"
                },
                "idRawMaterial": {
                    "type": "integer"
                },
                "parameterKuantitasPembentuk": {
                    "type": "number"
                }
            }
        },
        "manufaktur.DTOCustomerSimpan": {
            "type": "object",
            "required": [
                "customerCode",
                "nama"
            ],
            "properties": {
                "customerCode": {
                    "type": "string"
                },
                "kontak": {
                    "type": "string"
                },
                "nama": {
                    "type": "string"
                }
            }
        },
        "manufaktur.DTOMaterialSimpan": {
            "type": "object",
            "required": [
                "idPemasok",
                "kodeSKU",
                "namaMaterial",
                "unitSatuan"
            ],
            "properties": {
                "beratGSM": {
                    "type": "integer"
                },
                "idPemasok": {
                    "type": "integer"
                },
                "kodeSKU": {
                    "type": "string"
                },
                "lebarCM": {
                    "type": "number"
                },
                "namaMaterial": {
                    "type": "string"
                },
                "panjangCM": {
                    "type": "number"
                },
                "tebalCM": {
                    "type": "number"
                },
                "unitSatuan": {
                    "type": "string"
                }
            }
        },
        "manufaktur.DTOPemasokSimpan": {
            "type": "object",
            "required": [
                "namaEntitas",
                "supplierCode"
            ],
            "properties": {
                "kontak": {
                    "type": "string"
                },
                "namaEntitas": {
                    "type": "string"
                },
                "supplierCode": {
                    "type": "string"
                }
            }
        },
        "manufaktur.JenisDefectSnapshotDto": {
            "type": "object",
            "properties": {
                "aktif": {
                    "type": "boolean"
                },
                "id": {
                    "type": "string"
                },
                "kategoriDefectId": {
                    "type": "string"
                },
                "kodeDefect": {
                    "type": "string"
                },
                "kodeKategori": {
                    "type": "string"
                },
                "namaDefect": {
                    "type": "string"
                },
                "namaKategori": {
                    "type": "string"
                }
            }
        },
        "manufaktur.KategoriDefectSnapshotDto": {
            "type": "object",
            "properties": {
                "aktif": {
                    "type": "boolean"
                },
                "id": {
                    "type": "string"
                },
                "kodeKategori": {
                    "type": "string"
                },
                "namaKategori": {
                    "type": "string"
                },
                "urutanTampil": {
                    "type": "integer"
                }
            }
        },
        "manufaktur.KomposisiMaterialBOM": {
            "type": "object",
            "properties": {
                "dibuatPada": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "idParentMaterial": {
                    "type": "integer"
                },
                "idRawMaterial": {
                    "type": "integer"
                },
                "materialBaku": {
                    "$ref": "#/definitions/manufaktur.Material"
                },
                "parameterKuantitasPembentuk": {
                    "type": "number"
                },
                "parentMaterial": {
                    "$ref": "#/definitions/manufaktur.Material"
                }
            }
        },
        "manufaktur.LineProduksiSnapshotDto": {
            "type": "object",
            "properties": {
                "aktif": {
                    "type": "boolean"
                },
                "id": {
                    "type": "string"
                },
                "kodeLine": {
                    "type": "string"
                },
                "namaLine": {
                    "type": "string"
                },
                "urutanTampil": {
                    "type": "integer"
                }
            }
        },
        "manufaktur.MasterDataSnapshotDto": {
            "type": "object",
            "properties": {
                "jenisDefect": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/manufaktur.JenisDefectSnapshotDto"
                    }
                },
                "kategoriDefect": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/manufaktur.KategoriDefectSnapshotDto"
                    }
                },
                "lineProduksi": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/manufaktur.LineProduksiSnapshotDto"
                    }
                },
                "material": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/manufaktur.MaterialSnapshotDto"
                    }
                },
                "part": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/manufaktur.PartSnapshotDto"
                    }
                },
                "relasiPartDefect": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/manufaktur.RelasiPartDefectSnapshotDto"
                    }
                },
                "slotWaktu": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/manufaktur.SlotWaktuSnapshotDto"
                    }
                },
                "versiMasterData": {
                    "type": "string"
                }
            }
        },
        "manufaktur.Material": {
            "type": "object",
            "properties": {
                "beratGSM": {
                    "type": "integer"
                },
                "dibuatPada": {
                    "type": "string"
                },
                "diubahPada": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "idPemasok": {
                    "type": "integer"
                },
                "kodeSKU": {
                    "type": "string"
                },
                "lebarCM": {
                    "type": "number"
                },
                "namaMaterial": {
                    "type": "string"
                },
                "panjangCM": {
                    "type": "number"
                },
                "pemasok": {
                    "$ref": "#/definitions/manufaktur.Pemasok"
                },
                "tebalCM": {
                    "type": "number"
                },
                "unitSatuan": {
                    "type": "string"
                }
            }
        },
        "manufaktur.MaterialSnapshotDto": {
            "type": "object",
            "properties": {
                "aktif": {
                    "type": "boolean"
                },
                "id": {
                    "type": "string"
                },
                "kodeSKU": {
                    "type": "string"
                },
                "namaMaterial": {
                    "type": "string"
                }
            }
        },
        "manufaktur.PartSnapshotDto": {
            "type": "object",
            "properties": {
                "aktif": {
                    "type": "boolean"
                },
                "id": {
                    "type": "string"
                },
                "jumlahItemPerKanban": {
                    "type": "integer"
                },
                "kodeLineDefault": {
                    "type": "string"
                },
                "kodeMaterial": {
                    "type": "string"
                },
                "kodeProyek": {
                    "type": "string"
                },
                "kodeUnikPart": {
                    "type": "string"
                },
                "lineDefaultId": {
                    "type": "string"
                },
                "materialId": {
                    "type": "string"
                },
                "namaLineDefault": {
                    "type": "string"
                },
                "namaMaterial": {
                    "type": "string"
                },
                "namaPart": {
                    "type": "string"
                },
                "nomorPart": {
                    "type": "string"
                },
                "sumberData": {
                    "type": "string"
                }
            }
        },
        "manufaktur.Pemasok": {
            "type": "object",
            "properties": {
                "dibuatPada": {
                    "type": "string"
                },
                "diubahPada": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "kontak": {
                    "type": "string"
                },
                "namaEntitas": {
                    "type": "string"
                },
                "supplierCode": {
                    "type": "string"
                }
            }
        },
        "manufaktur.RelasiPartDefectSnapshotDto": {
            "type": "object",
            "properties": {
                "aktif": {
                    "type": "boolean"
                },
                "id": {
                    "type": "string"
                },
                "jenisDefectId": {
                    "type": "string"
                },
                "kodeDefect": {
                    "type": "string"
                },
                "kodeTampilanDefect": {
                    "type": "string"
                },
                "kodeUnikPart": {
                    "type": "string"
                },
                "partId": {
                    "type": "string"
                },
                "urutanTampil": {
                    "type": "integer"
                }
            }
        },
        "manufaktur.SlotWaktuSnapshotDto": {
            "type": "object",
            "properties": {
                "aktif": {
                    "type": "boolean"
                },
                "id": {
                    "type": "string"
                },
                "jamMulai": {
                    "type": "string"
                },
                "jamSelesai": {
                    "type": "string"
                },
                "kodeSlot": {
                    "type": "string"
                },
                "labelSlot": {
                    "type": "string"
                },
                "urutanTampil": {
                    "type": "integer"
                }
            }
        },
        "otentikasi.DataPermintaanLogin": {
            "type": "object",
            "properties": {
                "kata_sandi": {
                    "description": "Fallback sandi untuk login retro-kompatibel",
                    "type": "string",
                    "example": "admin"
                },
                "nip": {
                    "description": "Fallback NIP untuk login retro-kompatibel",
                    "type": "string",
                    "example": "2211019"
                },
                "sandi": {
                    "description": "Kata sandi akun",
                    "type": "string",
                    "example": "sandiRahasia123"
                },
                "surel": {
                    "description": "Surel akun terdaftar",
                    "type": "string",
                    "example": "operator@pgn.com"
                }
            }
        },
        "otentikasi.DataPermintaanLupaSandi": {
            "type": "object",
            "properties": {
                "kata_sandi": {
                    "description": "Fallback sandi baru retro-kompatibel",
                    "type": "string",
                    "example": "admin"
                },
                "nip": {
                    "description": "Fallback NIP untuk reset retro-kompatibel",
                    "type": "string",
                    "example": "2211019"
                },
                "sandiBaru": {
                    "description": "Kata sandi baru (Minimal 8 karakter)",
                    "type": "string",
                    "example": "sandiBaru123"
                },
                "surel": {
                    "description": "Surel akun terdaftar",
                    "type": "string",
                    "example": "operator@pgn.com"
                }
            }
        },
        "otentikasi.DataPermintaanRegistrasi": {
            "type": "object",
            "properties": {
                "kata_sandi": {
                    "description": "Kata sandi fallback (Retro-kompatibilitas)",
                    "type": "string",
                    "example": "admin"
                },
                "nama_lengkap": {
                    "description": "Nama lengkap pegawai (Opsional)",
                    "type": "string",
                    "example": "Leader QC"
                },
                "nip": {
                    "description": "Nomor Induk Pegawai (Fallback retro-kompatibilitas)",
                    "type": "string",
                    "example": "2211019"
                },
                "peran": {
                    "description": "Peran otorisasi: OPERATOR atau LEADER (Default: OPERATOR)",
                    "type": "string",
                    "example": "OPERATOR"
                },
                "sandi": {
                    "description": "Kata sandi minimal 8 karakter (Wajib jika kata_sandi kosong)",
                    "type": "string",
                    "example": "sandiRahasia123"
                },
                "surel": {
                    "description": "Surel resmi pegawai (Wajib jika NIP kosong)",
                    "type": "string",
                    "example": "operator@pgn.com"
                }
            }
        },
        "respon.DetailKesalahan": {
            "type": "object",
            "properties": {
                "field": {
                    "type": "string"
                },
                "pesan": {
                    "type": "string"
                }
            }
        },
        "respon.ResponStandar": {
            "type": "object",
            "properties": {
                "data": {},
                "errors": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "kesalahan": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/respon.DetailKesalahan"
                    }
                },
                "message": {
                    "type": "string"
                },
                "meta": {},
                "metadata": {},
                "pesan": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "success": {
                    "description": "Legacy fields untuk retro-kompatibilitas",
                    "type": "boolean"
                },
                "sukses": {
                    "type": "boolean"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "PGNServer API",
	Description:      "REST API untuk ekosistem manufaktur dan kontrol kualitas PGNServer.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
