basePath: /api/v1
definitions:
  model.Produk:
    properties:
      customer_id:
        type: string
      dibuat_pada:
        type: string
      id:
        type: string
      line_id:
        type: string
      lokasi_foto:
        type: string
      model:
        type: string
      nama_assy:
        type: string
      nama_part:
        type: string
      nomor_part:
        type: string
      nomor_unik:
        type: string
    type: object
  pengelola.ChecksheetInput:
    properties:
      details:
        items:
          properties:
            keterangan:
              type: string
            parameter_hasil:
              additionalProperties: true
              type: object
            proses:
              type: string
          required:
          - parameter_hasil
          - proses
          type: object
        type: array
      header:
        properties:
          line_id:
            type: string
          mesin_id:
            type: string
          produk_id:
            type: string
          shift:
            type: integer
          user_id:
            type: integer
        required:
        - line_id
        - mesin_id
        - produk_id
        - shift
        - user_id
        type: object
    required:
    - details
    - header
    type: object
  pengelola.LoginInput:
    properties:
      nip:
        type: string
      password:
        type: string
    required:
    - nip
    - password
    type: object
  utilitas.ResponsAPI:
    properties:
      data: {}
      pesan:
        type: string
      status:
        type: boolean
    type: object
host: localhost:8080
info:
  contact:
    email: support@pgn.co.id
    name: API Support
    url: http://www.pgn.co.id/support
  description: API Server untuk PGN (Produk Gagal & NG) Intelligence System.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: PGNServer API
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: Login menggunakan NIP dan Password untuk mendapatkan JWT
      parameters:
      - description: Credentials
        in: body
        name: login
        required: true
        schema:
          $ref: '#/definitions/pengelola.LoginInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utilitas.ResponsAPI'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/utilitas.ResponsAPI'
      summary: User Login
      tags:
      - Auth
  /produk:
    get:
      consumes:
      - application/json
      description: Mengambil semua data produk dari database
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utilitas.ResponsAPI'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utilitas.ResponsAPI'
      security:
      - BearerAuth: []
      summary: Ambil Semua Produk
      tags:
      - Produk
    post:
      consumes:
      - application/json
      description: Menyimpan data produk baru ke database
      parameters:
      - description: Data Produk
        in: body
        name: produk
        required: true
        schema:
          $ref: '#/definitions/model.Produk'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/utilitas.ResponsAPI'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utilitas.ResponsAPI'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utilitas.ResponsAPI'
      security:
      - BearerAuth: []
      summary: Tambah Produk Baru
      tags:
      - Produk
  /qc-tools/control-chart:
    get:
      consumes:
      - application/json
      description: Kalkulasi paralel UCL, LCL, dan Rata-rata menggunakan Goroutine
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utilitas.ResponsAPI'
      security:
      - BearerAuth: []
      summary: Ambil Data Control Chart
      tags:
      - QC-Tools
  /qc-tools/pareto:
    get:
      consumes:
      - application/json
      description: Mengambil data 80/20 cacat tertinggi menggunakan Goroutine
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utilitas.ResponsAPI'
      security:
      - BearerAuth: []
      summary: Ambil Data Pareto
      tags:
      - QC-Tools
  /qc/checksheet:
    post:
      consumes:
      - application/json
      description: Menyimpan data checksheet (Header & Detail) dalam satu transaksi
      parameters:
      - description: Data Checksheet
        in: body
        name: checksheet
        required: true
        schema:
          $ref: '#/definitions/pengelola.ChecksheetInput'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/utilitas.ResponsAPI'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utilitas.ResponsAPI'
      security:
      - BearerAuth: []
      summary: Simpan Checksheet QC
      tags:
      - QC
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
