basePath: /api/v1
definitions:
  model.BillOfMaterial:
    properties:
      material:
        $ref: '#/definitions/model.Material'
      material_id:
        type: string
      produk_id:
        type: string
      usage_qty:
        type: number
    type: object
  model.DefectMaster:
    properties:
      dibuat_pada:
        type: string
      id:
        type: string
      kategori:
        description: MATERIAL or PROCESS
        type: string
      nama_ng:
        type: string
    type: object
  model.Material:
    properties:
      dibuat_pada:
        type: string
      id:
        type: string
      nama_part:
        type: string
      nomor_unik:
        type: string
      potensi_defect:
        items:
          $ref: '#/definitions/model.DefectMaster'
        type: array
      satuan:
        type: string
      supplier_id:
        type: string
    type: object
  model.Produk:
    properties:
      assy_name:
        type: string
      bom:
        items:
          $ref: '#/definitions/model.BillOfMaterial'
        type: array
      customer_id:
        type: string
      dibuat_pada:
        type: string
      id:
        type: string
      line_id:
        type: string
      model:
        type: string
      nama_part:
        type: string
      nomor_part:
        type: string
      nomor_unik:
        type: string
    type: object
  pengelola.ChecksheetInput:
    properties:
      details:
        items:
          properties:
            defects:
              items:
                properties:
                  defect_id:
                    type: string
                  jumlah:
                    type: integer
                type: object
              type: array
            keterangan:
              type: string
            parameter_hasil:
              additionalProperties: true
              type: object
            proses:
              description: PRESS, SEWING, CUTTING
              type: string
          required:
          - parameter_hasil
          - proses
          type: object
        type: array
      header:
        properties:
          line_id:
            type: string
          produk_id:
            type: string
          shift:
            type: integer
          user_id:
            type: integer
        required:
        - line_id
        - produk_id
        - shift
        - user_id
        type: object
    required:
    - details
    - header
    type: object
  pengelola.LoginInput:
    properties:
      nip:
        type: string
      password:
        type: string
    required:
    - nip
    - password
    type: object
  utilitas.ResponsAPI:
    properties:
      data: {}
      pesan:
        type: string
      status:
        type: boolean
    type: object
host: localhost:8080
info:
  contact: {}
  description: API Server untuk PGN (Produk Gagal & NG) Intelligence System.
  title: PGNServer API
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: Login menggunakan NIP dan Password untuk mendapatkan JWT
      parameters:
      - description: Credentials
        in: body
        name: login
        required: true
        schema:
          $ref: '#/definitions/pengelola.LoginInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utilitas.ResponsAPI'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/utilitas.ResponsAPI'
      summary: User Login
      tags:
      - Auth
  /media/upload:
    post:
      consumes:
      - multipart/form-data
      description: Mengunggah file gambar ke folder penyimpanan
      parameters:
      - description: File gambar
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utilitas.ResponsAPI'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utilitas.ResponsAPI'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utilitas.ResponsAPI'
      security:
      - BearerAuth: []
      summary: Upload Media
      tags:
      - Media
  /produk:
    get:
      consumes:
      - application/json
      description: Mengambil semua data produk dari database
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utilitas.ResponsAPI'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utilitas.ResponsAPI'
      security:
      - BearerAuth: []
      summary: Ambil Semua Produk
      tags:
      - Produk
    post:
      consumes:
      - application/json
      description: Menyimpan data produk baru ke database
      parameters:
      - description: Data Produk
        in: body
        name: produk
        required: true
        schema:
          $ref: '#/definitions/model.Produk'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/utilitas.ResponsAPI'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utilitas.ResponsAPI'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utilitas.ResponsAPI'
      security:
      - BearerAuth: []
      summary: Tambah Produk Baru
      tags:
      - Produk
  /qc-tools/control-chart:
    get:
      consumes:
      - application/json
      description: Kalkulasi paralel UCL, LCL, dan Rata-rata menggunakan Goroutine
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utilitas.ResponsAPI'
      security:
      - BearerAuth: []
      summary: Ambil Data Control Chart
      tags:
      - QC-Tools
  /qc-tools/pareto:
    get:
      consumes:
      - application/json
      description: Mengambil data 80/20 cacat tertinggi menggunakan Goroutine
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utilitas.ResponsAPI'
      security:
      - BearerAuth: []
      summary: Ambil Data Pareto
      tags:
      - QC-Tools
  /qc/checksheet:
    post:
      consumes:
      - application/json
      description: Menyimpan data checksheet (Header & Detail) serta mencatat log
        defect secara otomatis
      parameters:
      - description: Data Checksheet
        in: body
        name: checksheet
        required: true
        schema:
          $ref: '#/definitions/pengelola.ChecksheetInput'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/utilitas.ResponsAPI'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utilitas.ResponsAPI'
      security:
      - BearerAuth: []
      summary: Simpan Checksheet QC & Log NG
      tags:
      - QC-Checksheet
  /qc/form-checksheet/{produk_id}:
    get:
      description: Mengambil potensi defect material (via BOM) dan defect proses secara
        paralel
      parameters:
      - description: ID Produk
        in: path
        name: produk_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utilitas.ResponsAPI'
      security:
      - BearerAuth: []
      summary: Ambil Form Checksheet Dinamis
      tags:
      - QC-Checksheet
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
